spring.application.name=SistemaDeGeolocalizacaoEJC

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sistemaGeolocalizacaoEJC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

server.port=${PORT:8080}

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE

spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}

osrm.url=${OSRM_URL:http://localhost:5000}
