spring.application.name=SistemaDeGeolocalizacaoEJC

spring.datasource.url=jdbc:postgresql://localhost:5432/sistemaGeolocalizacaoEJC
spring.datasource.username=postgres
spring.datasource.password=03032004
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=TRACE

spring.jpa.show-sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}

osrm.url=http://localhost:5000
