name: Geolocalization System CI/CD Front-end

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  compile:
    runs-on: ubuntu-latest
    name: Compile project front

    defaults:
      run:
        working-directory: front-end/project-for-ejcGeolocalization

    steps:
      - name: Checkout code front
        uses: actions/checkout@v4

      - name: Setup Node and cache front
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: front-end/project-for-ejcGeolocalization/package-lock.json

      - name: install dependecies
        run: npm ci

      - name: compile project front
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: Teste app

    defaults:
      run:
        working-directory: front-end/project-for-ejcGeolocalization

    steps:
      - name: Checkout code front
        uses: actions/checkout@v4

      - name: Setup Node and cache front
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: front-end/project-for-ejcGeolocalization/package-lock.json
      
      - name: install dependecies front
        run: npm ci

      - name: Run tests front
        run: npm test

  build:
    runs-on: ubuntu-latest
    name: build-app front

    needs:
      - compile
      - test

    defaults:
      run:
         working-directory: front-end/project-for-ejcGeolocalization

    steps:
      - name: Checkout code front
        uses: actions/checkout@v4

      - name: Setup Node and cache front
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: front-end/project-for-ejcGeolocalization/package-lock.json

      - name: install dependecies front
        run: npm ci

      - name: Build project front
        run: npm run build 


  deploy: 
    runs-on: ubuntu-latest
    name: deploy app
    needs: build

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: front-end/project-for-ejcGeolocalization

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel configuration
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"

      - name: Build for Vercel
        run: vercel build --prod --token="$VERCEL_TOKEN"

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"






      
      
    